# fly.toml app configuration file generated for ezyai on 2026-09-05T07:15:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ezyai'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  EZYAI_LOG_LEVEL = 'INFO'
  EZYAI_STATE_FILE = '/data/state.json'
  PORT = '8080'

[[mounts]]
  source = 'ezyai_state'
  destination = '/data'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true

[checks]
  [checks.http]
    method = 'GET'
    path = '/'
    grace_period = '30s'
    interval = '30s'
    timeout = '5s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
