#!/usr/bin/env sh
# Regenerate requirements.lock: the exact dependency set resolved for the
# image's Python (3.13) without installing anything locally. Run after any
# change to requirements.txt, then commit both files.
set -eu
cd "$(dirname "$0")/.."
report=$(mktemp)
python -m pip install --dry-run --ignore-installed --quiet \
  --python-version 3.13 --only-binary=:all: --target "$(mktemp -d)" \
  -r requirements.txt --report "$report"
python - "$report" <<'EOF'
import json, sys
r = json.load(open(sys.argv[1]))
pins = sorted(f"{i['metadata']['name'].lower()}=={i['metadata']['version']}"
              for i in r["install"])
with open("requirements.lock", "w") as fh:
    fh.write("# Generated by scripts/lock.sh from requirements.txt for Python 3.13.\n")
    fh.write("# Do not edit by hand.\n")
    fh.write("\n".join(pins) + "\n")
print(f"wrote requirements.lock ({len(pins)} pins)")
EOF
rm -f "$report"
